/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.let.helper;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import me.let.gen.helper.SimpleUniqueStringGenerator;

public class SimpleStringGeneratorTest {
    private SimpleUniqueStringGenerator simpleUniqueStringGenerator;

    @Before
    public void init(){
        this.simpleUniqueStringGenerator = new SimpleUniqueStringGenerator();
    }

    @Test public void test_generateValid() {
        final int length = 100;
        final String str = simpleUniqueStringGenerator.generate(100);
        assertNotNull(str);
        assertEquals(length, str.length());
    }

    @Test(expected = IllegalArgumentException.class)
    public void test_generateInvalidLength() {
        simpleUniqueStringGenerator.generate(0);
    }
}
